config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'welcome#home'
  resources :discussions do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :discussions, dependent: :destroy
  has_many :comments, dependent: :destroy


  def owns_discussion?(discussion)
    id == discussion.user_id
  end

  def owns_comment?(comment)
    id == comment.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_discussion
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]
  before_action :set_current_user

  def create
    @comment = @discussion.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to discussion_path(@discussion)
    else
      flash[:notice] = "Blah blah blah"
      redirect_to discussion_path(@discussion)
    end
  end

  def destroy
    @comment.destroy
    redirect_to discussion_path(@discussion)
  end

  def edit
  end

  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to discussion_path(@discussion)
    else
      render 'edit'
    end
  end

  private

  def find_discussion
    @discussion = Discussion.find(params[:discussion_id])
  end

  def find_comment
    @comment = @discussion.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = "You do not have permission to perform that action"
      redirect_to @discussion
    end
  end

  def set_current_user
    @user = current_user
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user
  before_action :discussion_owner, only: [:destroy, :edit, :update]

  def discussions
    @discussions = Discussions.order(created_at: :desc)
  end

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @comments = Comment.where(discussion_id: @discussion)
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:headline, :content)
  end

  def set_current_user
    @user = current_user
  end

  def discussion_owner
    unless current_user.id == @discussion.user_id
    flash[:notice] = "You do not have permission to perform that action"
    redirect_to @discussion
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_discussions = @user.discussions
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div id="comment_count">
  <small>
    <%= pluralize(@comments.count, "Comment") %>
  </small>
</div>

<% @discussion.comments.each do |comment| %>
  <div class="comment">
    <div id="comment_content">
      <%= comment.content %>
    </div>
  <small>
    <p>
      <span class=chip>
        <%= gravatar_for comment.user %>
        <%= comment.user.name %>
      </span> at <%= comment.created_at.strftime("%H:%M %Z") %> on <%= comment.created_at.strftime("%d/%m/%Y") %>
    </p>
  </small>
  <% if current_user == comment.user %>
    <%= link_to "Delete Comment", [comment.discussion, comment], method: :delete, :class => "waves-effect waves-light btn-small" %>
    <%= link_to "Edit Comment", edit_discussion_comment_path(comment.discussion, comment), :class => "waves-effect waves-light btn-small" %>
  <% end %>
  </div>

<% end %>



<h5 id="add_comment_text">Add Comment</h5>
<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@discussion, @discussion.comments.build]) do |form| %>
  <%= form.text_area :content %>
  <div id="comment_submit_button">
    <button class="waves-effect waves-light btn-small" type="submit" name="action">Submit</button>
  </div>
  <br>
<% end %>

app/views/comments/edit.html.erb
<h5>Edit Comment</h5>

<%= form_for([@discussion, @comment]) do |form| %>
  <%= form.text_area :content %>
  <div id="comment_submit_button">
    <button class="waves-effect waves-light btn-small" type="submit" name="action">Submit</button>
  </div>
  <br>
  <br>
  <div id="comment_back_button">
    <%= link_to 'Back', discussions_path, :class => "waves-effect waves-light btn-small" %>
  </div>
  <br>
<% end %>

app/views/discussions/_discussion.html.erb
<% obj.each do |discussion| %>
  <div class="row">
    <div class="col s12" class="z-depth-4" id="discussion_preview">
      <div class="well well-lg">
        <div class="discussion-title blue darken-2 z-depth-2">
          <h4><%= link_to discussion.headline, discussion_path(discussion) %></h4>
        </div>
        <div class="discussion-body">
          <%= truncate(discussion.content, length: 100) %>
          <div class="discussion-meta-details">
            <small>
              <p>
                <span class=chip>
                  <%= gravatar_for discussion.user %>
                  <%= discussion.user.name %>
                </span> at <%= discussion.created_at.strftime("%H:%M %Z") %> on <%= discussion.created_at.strftime("%d/%m/%Y") %>
              </p>
            </small>
          </div>
        </div>
        <% if current_user.owns_discussion?(discussion) %>
          <div class="article-actions">
            <%= link_to 'Edit', edit_discussion_path(discussion), class: 'waves-effect waves-light btn' %> | 
            <%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline, id: :discussion_headline, :required => true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :discussion_content %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit "Submit", :id => "edit_submit_btn", class: 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h4>Editing Discussion</h4>

<%= render 'form', discussion: @discussion %>
<div class="edit_buttons">
  <%= link_to 'Show', @discussion, :id => "edit_show_btn", :class => "waves-effect waves-light btn-small"%> | 
  <%= link_to 'Back', discussions_path, :id => "edit_back_btn", :class => "waves-effect waves-light btn-small" %>
</div>

app/views/discussions/index.html.erb
<div id="new_discussion_button">
  <%= link_to 'New Discussion', new_discussion_path, class: 'waves-effect waves-light btn' %>
</div>
<div>
  <h2>Discussions</h2>
</div>
<%= render 'discussion', obj: @discussions.order(created_at: :desc) %>

app/views/discussions/new.html.erb
<h4>New Discussion</h4>

<%= render 'form', discussion: @discussion %>
<br>
<%= link_to 'Back', discussions_path, :class => "waves-effect waves-light btn-small" %>

app/views/discussions/oldindex.html.erb
<h4>Discussions</h4>

<%= link_to 'New Discussion', new_discussion_path, class: 'waves-effect waves-light btn' %>

<table id="discussion_index" class="striped">
  <thead>
    <tr>
      <th>Topic</th>
      <th>Poster</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= link_to "#{discussion.headline}", discussion %></td>
        <td><%= discussion.user.name %></td>
        <td>
          <% if current_user.owns_discussion?(discussion) %>
            <%= link_to 'Edit', edit_discussion_path(discussion), class: 'waves-effect waves-light btn' %>
            <%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_discussion_path, class: 'waves-effect waves-light btn' %>

app/views/discussions/show.html.erb
<div class="discussion_show z-depth-3 grey lighten-2">
  <div class="discussion_headline blue darken-2 z-depth-2">
    <h3><%= @discussion.headline %></h3>
  </div>
  <div class="discussion_content">
    <%= @discussion.content %>
  </div>

  <div class="dicussion-meta-details">
    <small>
      <p>
        <span class=chip>
          <%= gravatar_for @discussion.user %>
          <%= @discussion.user.name %>
        </span> at <%= @discussion.created_at.strftime("%H:%M %Z") %> on <%= @discussion.created_at.strftime("%d/%m/%Y") %>
      </p>
    </small>
  </div>
</div>

<%= render 'comments/comment' %>

<% if current_user.id == @discussion.user_id %>
  <%= link_to 'Edit', edit_discussion_path(@discussion), :class => "waves-effect waves-light btn-small" %> | 
<% end %>  
<%= link_to 'Back', discussions_path, :class => "waves-effect waves-light btn-small" %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Presumptuous</h5>
        <p class="grey-text text-lighten-4">© 2018 Chris Webb</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://chris-webb.herokuapp.com/">My Site</a></li>
          <li><a class="grey-text text-lighten-3" href="https://soundcloud.com/webbc99">My SoundCloud</a></li>
          <li><a class="grey-text text-lighten-3" href="https://rubyonrails.org/">Rails</a></li>
          <li><a class="grey-text text-lighten-3" href="https://materializecss.com/">Materialize CSS</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <p>Some text that no one reads but makes a website look complete</p>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presumptuous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Prompt:400,700|Quicksand:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="navbar-fixed">
      <nav class="blue darken-2">
        <div class="nav-wrapper">
          <div class="container">
            <%= link_to "Presumptuous", root_path, class: "brand-logo" %>
            <ul class="right hide-on-med-and-down">
              <% if current_user %>
                <li>
                  <div class=chip>
                    <%= gravatar_for @user %>
                    <%= current_user.name %>
                  </div>
                </li>
                <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Log In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
              <li><%= link_to "Forum", discussions_path %></li>
              <li><%= link_to "Home", root_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/_application_form.html.erb
<div class="form-popup" id="app_form">
  <form id="application_form">
    <div id="email">
      <label>
        Email: 
        <input name="email" type="email" placeholder="example@example.com">
      </label>
    </div>
    <div id="character_name">
      <label>
        Character Name: 
        <input name="character_name" type="text" placeholder="Leeroy">
      </label>
    </div>
    <div id="battle_net_id">
      <label>
        Battle.Net ID: 
        <input name="battle_net_id" type="text" placeholder="Example#2345">
      </label>
    </div>
    <div id="app_type">
      <label for="raider"><span>Raider: </span><input class="with-gap" name="app_type" id="raider" type="radio" value="raider"></label>
      <label for="social"><span>Social: </span><input class="with-gap" name="app_type" id="social" type="radio" value="social" checked="true"></label>
    </div>
    <br>
    <div id="submit_button">
      <button class="waves-effect waves-light btn">Submit</button>
    </div>
    <br>
  </form>
</div>

app/views/welcome/_guild_info.html.erb
<div id="guildInfo">
<!--   <h2 id="guildInfoOne">
    <span class="guildName">P</span>
    <span class="guildName">r</span>
    <span class="guildName">e</span>
    <span class="guildName">s</span>
    <span class="guildName">u</span>
    <span class="guildName">m</span>
    <span class="guildName">p</span>
    <span class="guildName">t</span>
    <span class="guildName">u</span>
    <span class="guildName">o</span>
    <span class="guildName">u</span>
    <span class="guildName">s</span>
  </h2> -->

  <h3 id="guildInfoTwo">
    <span class="shadowsong">S</span>
    <span class="shadowsong">h</span>
    <span class="shadowsong">a</span>
    <span class="shadowsong">d</span>
    <span class="shadowsong">o</span>
    <span class="shadowsong">w</span>
    <span class="shadowsong">s</span>
    <span class="shadowsong">o</span>
    <span class="shadowsong">n</span>
    <span class="shadowsong">g</span>
    <span class="slash">/</span>
    <span class="aszune">A</span>
    <span class="aszune">s</span>
    <span class="aszune">z</span>
    <span class="aszune">u</span>
    <span class="aszune">n</span>
    <span class="aszune">e</span>
  </h3>

  <h3 id="guildInfoThree">
    <span class="guildRegion">E</span>
    <span class="guildRegion">U</span>
    <span class="slash">/</span>
    <span class="guildFaction">A</span>
    <span class="guildFaction">l</span>
    <span class="guildFaction">l</span>
    <span class="guildFaction">i</span>
    <span class="guildFaction">a</span>
    <span class="guildFaction">n</span>
    <span class="guildFaction">c</span>
    <span class="guildFaction">e</span>
  </h3>
</div>

app/views/welcome/home.html.erb
<%= render 'guild_info' %>
<div id="blurb">
  <p>Hi! We are Presumptuous. 8/8 Uldir Normal! Check out the <%= link_to 'forum', discussions_path %>!</p>
</div>

<button class="open-button waves-effect waves-light btn" id="join_us" onclick="openForm()">Join Us!</button>
<%= render 'application_form' %>

<%= image_tag ('image_2.png'), :class => 'pic w3-animate-fading', :id => 'pic_1' %>
<%= image_tag ('image_4.png'), :class => 'pic w3-animate-fading', :id => 'pic_2' %>
<%= image_tag ('image_1.png'), :class => 'pic w3-animate-fading', :id => 'pic_3' %>
<%= image_tag ('lazarus.jpg'), :class => 'pic w3-animate-fading', :id => 'pic_4' %>

<script>
var slideIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("pic");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > x.length) {slideIndex = 1}
    x[slideIndex-1].style.display = "block";
    setTimeout(carousel, 9000);
};
</script>